name: modal_dialog
description: A minimalist modal dialog system.
version: 0.0.1
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/gchumillas

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
