name: mdialog
description: A minimalist modal dialog system.
version: 0.0.1
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/gchumillas

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  domelement: ^0.2.3
  dart_sass_transformer: ^0.5.0

transformers:
  - dart_sass_transformer:
      compass: true

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
